#pragma once

typedef enum {
    INK_REFRESH_STRATEGY_NONE = 0,
    INK_REFRESH_STRATEGY_PAGE_TRANSITION_FULL,
    INK_REFRESH_STRATEGY_BW_UI_PAGE_FAST,
    INK_REFRESH_STRATEGY_BW_UI_LIST_LOCAL,
    INK_REFRESH_STRATEGY_OVERLAY_LOCAL_UPDATE,
    INK_REFRESH_STRATEGY_READER_TEXT_TURN,
    INK_REFRESH_STRATEGY_READER_HOLD_PREVIEW,
    INK_REFRESH_STRATEGY_READER_TEXT_CLEANUP,
    INK_REFRESH_STRATEGY_GRAY_IMAGE_PREVIEW,
    INK_REFRESH_STRATEGY_GRAY_IMAGE_INTERRUPTIBLE,
    INK_REFRESH_STRATEGY_GRAY_IMAGE_SETTLE,
    INK_REFRESH_STRATEGY_LAB_EXPLICIT_MODE,
} ink_refresh_strategy_t;
