#!/usr/bin/env python3
"""Generate fixed 1bpp bitmap assets for the embedded UI."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


DEFAULT_FONT_PATH = Path(__file__).resolve().parent / "testdata" / "LXGWWenKai-ui-subset.ttf"


@dataclass(frozen=True)
class Phrase:
    text: str
    pixel_size: int


PHRASES = (
    Phrase("启动器", 24),
    Phrase("阅读 / 相册", 16),
    Phrase("书库", 12),
    Phrase("相册", 12),
    Phrase("打开图书与最近阅读", 16),
    Phrase("浏览 TF 卡灰阶图片", 16),
    Phrase("正在加载", 16),
    Phrase("字体不可用", 16),
    Phrase("未找到图片", 16),
    Phrase("未找到可显示图片", 16),
    Phrase("未找到书籍", 16),
    Phrase("SD 卡错误", 16),
    Phrase("书籍格式错误", 16),
)


def _pack_1bpp(image: Image.Image, threshold: int = 128) -> bytes:
    width, height = image.size
    stride = (width + 7) // 8
    bitmap = bytearray(stride * height)
    pixels = image.load()
    for y in range(height):
        for x in range(width):
            if pixels[x, y] < threshold:
                bitmap[y * stride + x // 8] |= 0x80 >> (x % 8)
    return bytes(bitmap)


def _render(phrase: Phrase, font_path: Path) -> tuple[int, int, bytes]:
    font = ImageFont.truetype(str(font_path), phrase.pixel_size)
    probe = Image.new("L", (1, 1), 255)
    probe_draw = ImageDraw.Draw(probe)
    left, top, right, bottom = probe_draw.textbbox((0, 0), phrase.text, font=font)
    width = right - left
    height = bottom - top

    image = Image.new("L", (width, height), 255)
    ImageDraw.Draw(image).text((-left, -top), phrase.text, font=font, fill=0)
    return width, height, _pack_1bpp(image)


def _format_bitmap(name: str, bitmap: bytes) -> str:
    lines = []
    for offset in range(0, len(bitmap), 12):
        values = ", ".join(f"0x{value:02X}" for value in bitmap[offset : offset + 12])
        lines.append(f"    {values},")
    body = "\n".join(lines)
    return f"static const uint8_t {name}[] = {{\n{body}\n}};"


def _c_string(value: str) -> str:
    return "".join(f"\\x{byte:02X}" for byte in value.encode("utf-8"))


def _validate_range(field: str, value: int, maximum: int) -> None:
    if not 1 <= value <= maximum:
        raise ValueError(f"{field} must be between 1 and {maximum}, got {value}")


def generate(font_path: Path, output_path: Path) -> None:
    rendered = []
    for phrase in PHRASES:
        _validate_range("pixel_size", phrase.pixel_size, 0xFF)
        width, height, bitmap = _render(phrase, font_path)
        _validate_range("width", width, 0xFFFF)
        _validate_range("height", height, 0xFFFF)
        rendered.append((width, height, bitmap))
    bitmaps = [
        _format_bitmap(f"s_bitmap_{index}", bitmap)
        for index, (_, _, bitmap) in enumerate(rendered)
    ]
    entries = []
    for index, (phrase, (width, height, _)) in enumerate(zip(PHRASES, rendered)):
        entries.append(
            f'    {{"{_c_string(phrase.text)}", {phrase.pixel_size}, '
            f"{width}, {height}, s_bitmap_{index}}},"
        )

    source = "\n".join(
        [
            "/* Generated by tools/generate_ui_text_bitmaps.py. Do not edit. */",
            '#include "ink_ui_text_assets.h"',
            "",
            "#include <stddef.h>",
            "#include <string.h>",
            "",
            "\n\n".join(bitmaps),
            "",
            "static const ink_ui_text_asset_t s_assets[] = {",
            *entries,
            "};",
            "",
            "const ink_ui_text_asset_t *ink_ui_text_asset_find(const char *text, uint8_t pixel_size)",
            "{",
            "    if (text == NULL) {",
            "        return NULL;",
            "    }",
            "",
            "    for (size_t i = 0; i < sizeof(s_assets) / sizeof(s_assets[0]); ++i) {",
            "        if (s_assets[i].pixel_size == pixel_size && strcmp(s_assets[i].text, text) == 0) {",
            "            return &s_assets[i];",
            "        }",
            "    }",
            "    return NULL;",
            "}",
            "",
        ]
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(source, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", default=DEFAULT_FONT_PATH, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    generate(args.font, args.output)


if __name__ == "__main__":
    main()
